/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/ba3eHm9qBGc
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Chivo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"

export function Search() {
  return (
    <div className="flex flex-col items-center justify-center h-[100dvh] bg-gray-100 dark:bg-gray-800">
      <div className="max-w-md w-full px-4 sm:px-6 lg:px-8">
        <div className="space-y-4 text-center">
          <h1 className="text-3xl font-bold tracking-tight text-gray-900 dark:text-gray-50">
            Cari Yhahah
          </h1>
          <p className="text-gray-500 dark:text-gray-400">
            Learning path pake ai cuy.
          </p>
        </div>
        <form className="mt-8 space-y-4">
          <div>
            <label className="sr-only" htmlFor="url">
              Long URL
            </label>
            <div className="relative rounded-md shadow-sm">
              <input
                className="block w-full rounded-md border-gray-300 pl-3 pr-12 py-2 text-gray-900 placeholder-gray-500 focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm dark:bg-gray-700 dark:text-gray-50 dark:placeholder-gray-400"
                id="url"
                placeholder="Sedang belajar apa hari ini"
                required
                type="url"
              />
              <div className="absolute inset-y-0 right-0 flex items-center pr-0">
                <Button className="rounded-md px-4 py-2" type="submit">
                  Letsgo
                </Button>
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
  );
}
